name: DonateDuration
version: 1.2.1
main: com.kusokmedi.donateduration.DonateDuration
api-version: '1.16'
author: KusokMedi
website: github.com/kusokmedi/donduration
softdepend: [PlaceholderAPI, LuckPerms]

commands:
  donateduration:
    description: Main plugin command
    aliases: [dd]
    usage: /donateduration [reload]
