name: DonateDuration
version: 2.1
main: com.kusokmedi.donateduration.DonateDuration
api-version: '1.20'
author: KusokMedi
website: github.com/kusokmedi/donduration
description: Отображает оставшееся время донат-статуса через PlaceholderAPI
softdepend: [PlaceholderAPI, LuckPerms]

commands:
  donateduration:
    description: Главная команда плагина
    aliases: [dd]
    usage: /donateduration [reload|help]
    permission: donateduration.admin

permissions:
  donateduration.reload:
    description: Право на перезагрузку конфигурации
    default: op
  donateduration.admin:
    description: Доступ к командам плагина
    default: op
    children:
      - donateduration.reload
